import React, { useState } from 'react';
import {
  render, BlockStack, Button, TextField, Banner, Text, InlineStack, Divider,
  useExtensionApi, useApplyDiscountCodeChange,
  useCartLines,
  useTotalAmount,
  useAttributes,
} from '@shopify/ui-extensions-react/checkout';

/**
 * Entry point for the Checkout UI Extension.
 * Target: purchase.checkout.block.render
 */
render('purchase.checkout.block.render', () => <GiftCardRedeem />);

export default function GiftCardRedeem() {
  const lines = useCartLines(); // Returns an array of items in the cart
  const total = useTotalAmount(); // Returns the subtotal, taxes, and final total
  console.log("Current Cart Items:", lines);
  console.log("Total to pay:", total.amount);

  // Access session tokens for secure backend communication
  const { sessionToken } = useExtensionApi() as any;
  // Shopify hook to manipulate discount codes in the checkout state
  const applyDiscountCodeChange = useApplyDiscountCodeChange();

  const [cardNumber, setCardNumber] = useState("");
  const [pinCode, setPinCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [statusMessage, setStatusMessage] = useState<any>(null);
  const [appliedCards, setAppliedCards] = useState<any[]>([]);

  const APP_URL = "https://night-prepare-ben-waters.trycloudflare.com"; // To be replaced by the url of the tunnel cloudflare provided when projet is started locally.

  /**
   * Validates the card with the Ogloba API and applies it to the Shopify checkout.
   * Logic: Our backend validates the balance -> creates a dynamic Shopify discount -> 
   * returns the code to be applied here.
   */
  const handleApply = async () => {
    if (!cardNumber) return;
    setLoading(true); 
    setStatusMessage(null);

    try {
      const token = await sessionToken.get();
      const response = await fetch(`${APP_URL}/api/redemption`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify({ cardNumber, pinCode }),
      });

      const data = await response.json();
      if (data.success) {
        // Apply the dynamic discount code generated by the backend to the Shopify cart
        await applyDiscountCodeChange({ type: "addDiscountCode", code: data.discountCode });
        
        // Track locally to allow users to remove it
        setAppliedCards([...appliedCards, { ...data, last4: cardNumber.slice(-4) }]);
        setCardNumber(""); 
        setPinCode("");
        setStatusMessage({ type: "success", text: "Card applied!" });
      } else {
        setStatusMessage({ type: "error", text: data.message });
      }
    } catch (err) {
      console.error("DEBUG ERR:", err); 
      setStatusMessage({ type: "error", text: "Technical error" });
    } finally { 
      setLoading(false); 
    }
  };

  /**
   * Handles the removal of a gift card.
   * Logic: Removes the discount from Shopify AND notifies the backend 
   * to void the transaction on the Ogloba side.
   */
  const handleRemove = async (card: any) => {
    try {
      const token = await sessionToken.get();
      
      // 1. Remove the discount code from the Shopify Checkout session
      await applyDiscountCodeChange({ type: "removeDiscountCode", code: card.discountCode });
      
      // 2. Notify our API to trigger a 'cancelTransaction' on Ogloba
      await fetch(`${APP_URL}/api/cancel-redemption`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify({ discountCode: card.discountCode }),
      });

      setAppliedCards(appliedCards.filter(c => c.discountCode !== card.discountCode));
    } catch (err) {
      console.error("Error during removal", err);
    }
  };

  const handleCardNumberChange = (value: string) => {
    setCardNumber(value);
    if (statusMessage) setStatusMessage(null);
  };

  const handlePinCodeChange = (value: string) => {
    setPinCode(value);
    if (statusMessage) setStatusMessage(null);
  };

  return (
    <BlockStack spacing="base">
      <TextField label="Gift Card Number" value={cardNumber} onChange={handleCardNumberChange} />
      <TextField label="PIN" value={pinCode}  onChange={handlePinCodeChange} />
      
      {statusMessage && <Banner status={statusMessage.type === "error" ? "critical" : "success"}>{statusMessage.text}</Banner>}

      <Button onPress={handleApply} loading={loading} disabled={!cardNumber || loading}>
        Apply Card
      </Button>

      {appliedCards.length > 0 && (
        <BlockStack spacing="tight">
          <Divider />
          <Text size="medium" emphasis="bold">Applied Cards:</Text>
          {appliedCards.map((card, index) => (
            <InlineStack key={index} inlineAlignment="space-between">
              <Text>****{card.last4} ({card.amount}€)</Text>
              <Button kind="secondary" size="minor" onPress={() => handleRemove(card)}>Remove</Button>
            </InlineStack>
          ))}
        </BlockStack>
      )}
    </BlockStack>
  );
}